properties:
  - repo-link: 

dependencies:
#Generic Microservices
  - name: zk
    version: 1.11.0-21
    repository: ${repo-link}
  - name: kf
    version: 1.12.0-12
    repository: ${repo-link}
  - name: pm-server
    version: 3.1.0+13
    repository: ${repo-link}
#Custom Microservices
  - name: stream-data-processor
    version: 0.1.0
    repository: ./
  - name: pm-metric-processor
    version: 0.1.0
    repository: ./
#   - name: ml-anomaly-detection
#     version: 0.1.0
#     repository: ./
